// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS9ENO1b8JUNVmGrCohAl3G_v9tTzmTGI',
    appId: '1:82366362213:web:dd1b611bb92d6f6156cc8c',
    messagingSenderId: '82366362213',
    projectId: 'ecommerce-6ddb5',
    authDomain: 'ecommerce-6ddb5.firebaseapp.com',
    databaseURL: 'https://ecommerce-6ddb5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-6ddb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD54bmK-RD2STwFisdv9Mb_C9eaSnYC2Ic',
    appId: '1:82366362213:android:1de26bdd3c1dda5b56cc8c',
    messagingSenderId: '82366362213',
    projectId: 'ecommerce-6ddb5',
    databaseURL: 'https://ecommerce-6ddb5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-6ddb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOn780lJ_QgSTTJJy8wfHP8QkEQ26NNWQ',
    appId: '1:82366362213:ios:97d150889be1982256cc8c',
    messagingSenderId: '82366362213',
    projectId: 'ecommerce-6ddb5',
    databaseURL: 'https://ecommerce-6ddb5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-6ddb5.appspot.com',
    iosClientId: '82366362213-b9mcds5bu7gru9st4okc9a9a0rp808a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOn780lJ_QgSTTJJy8wfHP8QkEQ26NNWQ',
    appId: '1:82366362213:ios:8b7441d234aeaed056cc8c',
    messagingSenderId: '82366362213',
    projectId: 'ecommerce-6ddb5',
    databaseURL: 'https://ecommerce-6ddb5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-6ddb5.appspot.com',
    iosClientId: '82366362213-ck459u1k8mkllb6lsecii6cappdbi4dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFirebase.RunnerTests',
  );
}
